/**
 * „Federwissen" — der Fragenvorrat.
 *
 * Zwei Sorten, weil zwei Sorten Spaß:
 *
 *   WISSEN     Eine Frage, vier Antworten, eine davon stimmt. Im Datensatz
 *              steht die richtige immer an erster Stelle — das macht die
 *              Liste lesbar und pflegbar. Gemischt wird erst beim Anzeigen,
 *              und zwar mit dem Runden-Seed, damit auf beiden Geräten
 *              dieselbe Reihenfolge steht.
 *
 *   SCHAETZEN  Eine Zahl, die kaum jemand genau weiß, aber fast jeder auf
 *              die Größenordnung trifft. Hier gibt es keine falsche Antwort,
 *              nur nähere und weitere — deshalb Teilpunkte statt alles oder
 *              nichts. Das ist der Grund, warum überhaupt beide Sorten drin
 *              sind: Wissensfragen kennt man oder nicht, Schätzfragen kann
 *              man spielen.
 *
 * Zum Schwierigkeitsgrad: Die Latte liegt bewusst über „Hauptstadt von
 * Frankreich" und unter „Ordnungszahl von Ruthenium". Ziel ist die Frage,
 * bei der man kurz überlegt und dann doch draufkommt — oder eben knapp
 * danebenliegt und sich ärgert. Beides erzählt man dem anderen weiter.
 *
 * Feld für Feld:
 *   WISSEN     f Frage · a [richtig, falsch, falsch, falsch] · t Thema
 *   SCHAETZEN  f Frage · w wahrer Wert · e Einheit · t Thema · z Zusatz
 */

/** Wissensfragen. `a[0]` ist immer richtig. */
export const WISSEN = [
  /* ── Erde und Orte ───────────────────────────────────── */
  { f: 'Welches Land hat die längste Küstenlinie der Welt?', t: 'Geografie',
    a: ['Kanada', 'Russland', 'Indonesien', 'Australien'] },
  { f: 'Wie heißt die Hauptstadt von Kanada?', t: 'Geografie',
    a: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'] },
  { f: 'In welchem Land liegt Machu Picchu?', t: 'Geografie',
    a: ['Peru', 'Bolivien', 'Chile', 'Ecuador'] },
  { f: 'Welcher See ist der tiefste der Erde?', t: 'Geografie',
    a: ['Baikalsee', 'Kaspisches Meer', 'Tanganjikasee', 'Titicacasee'] },
  { f: 'Auf welchem Kontinent liegen die meisten Länder?', t: 'Geografie',
    a: ['Afrika', 'Asien', 'Europa', 'Südamerika'] },
  { f: 'Welches Bundesland ist flächenmäßig das größte?', t: 'Geografie',
    a: ['Bayern', 'Niedersachsen', 'Baden-Württemberg', 'Brandenburg'] },
  { f: 'Welches Land liegt nicht am Nil?', t: 'Geografie',
    a: ['Nigeria', 'Ägypten', 'Sudan', 'Uganda'] },
  { f: 'Welche dieser Städte liegt nicht in der Schweiz?', t: 'Geografie',
    a: ['Innsbruck', 'Winterthur', 'Luzern', 'Chur'] },
  { f: 'Welche ist die größte Insel der Welt?', t: 'Geografie',
    a: ['Grönland', 'Neuguinea', 'Borneo', 'Madagaskar'] },
  { f: 'Welche europäische Hauptstadt liegt am weitesten nördlich?', t: 'Geografie',
    a: ['Reykjavík', 'Helsinki', 'Oslo', 'Stockholm'] },
  { f: 'Welches Land hat heute die meisten Einwohner?', t: 'Geografie',
    a: ['Indien', 'China', 'USA', 'Indonesien'] },
  { f: 'Welcher Fluss ist innerhalb Deutschlands am längsten?', t: 'Geografie',
    a: ['Rhein', 'Elbe', 'Donau', 'Main'] },
  { f: 'Welche Stadt nennt man „die ewige Stadt"?', t: 'Geografie',
    a: ['Rom', 'Athen', 'Jerusalem', 'Istanbul'] },
  { f: 'Welches Land produziert weltweit den meisten Kaffee?', t: 'Geografie',
    a: ['Brasilien', 'Vietnam', 'Kolumbien', 'Äthiopien'] },
  { f: 'In welchem Land liegt die Atacama-Wüste?', t: 'Geografie',
    a: ['Chile', 'Peru', 'Namibia', 'Mexiko'] },
  { f: 'Welche Meerenge trennt in Istanbul Europa von Asien?', t: 'Geografie',
    a: ['Bosporus', 'Dardanellen', 'Straße von Gibraltar', 'Öresund'] },
  { f: 'Welches ist der kleinste Staat der Welt?', t: 'Geografie',
    a: ['Vatikanstadt', 'Monaco', 'San Marino', 'Liechtenstein'] },
  { f: 'Welcher Berg ist der höchste Afrikas?', t: 'Geografie',
    a: ['Kilimandscharo', 'Mount Kenya', 'Ruwenzori', 'Atlas'] },
  { f: 'Welches Meer ist das salzigste?', t: 'Geografie',
    a: ['Totes Meer', 'Rotes Meer', 'Mittelmeer', 'Ostsee'] },
  { f: 'Welche Wüste ist die größte der Erde?', t: 'Geografie',
    a: ['die Antarktis', 'die Sahara', 'die Gobi', 'die Arabische Wüste'] },
  { f: 'Durch welche Stadt fließt die Moldau?', t: 'Geografie',
    a: ['Prag', 'Budapest', 'Krakau', 'Bratislava'] },
  { f: 'Welcher Kanal verbindet Mittelmeer und Rotes Meer?', t: 'Geografie',
    a: ['Suezkanal', 'Panamakanal', 'Kieler Kanal', 'Korinth-Kanal'] },
  { f: 'Welche Stadt liegt auf zwei Kontinenten?', t: 'Geografie',
    a: ['Istanbul', 'Kairo', 'Athen', 'Baku'] },
  { f: 'Wie heißt die Hauptstadt Australiens?', t: 'Geografie',
    a: ['Canberra', 'Sydney', 'Melbourne', 'Perth'] },
  { f: 'Welches Land ist flächenmäßig das zweitgrößte der Welt?', t: 'Geografie',
    a: ['Kanada', 'China', 'USA', 'Brasilien'] },
  { f: 'An welchem Fluss liegt Dresden?', t: 'Geografie',
    a: ['Elbe', 'Saale', 'Spree', 'Havel'] },
  { f: 'Welches Land grenzt nicht an Deutschland?', t: 'Geografie',
    a: ['Ungarn', 'Tschechien', 'Luxemburg', 'Dänemark'] },
  { f: 'Wie heißt die Hauptstadt Neuseelands?', t: 'Geografie',
    a: ['Wellington', 'Auckland', 'Christchurch', 'Dunedin'] },

  /* ── Was mal passiert ist ────────────────────────────── */
  { f: 'In welchem Jahr fiel die Berliner Mauer?', t: 'Geschichte',
    a: ['1989', '1987', '1990', '1991'] },
  { f: 'Wer flog als erster Mensch ins All?', t: 'Geschichte',
    a: ['Juri Gagarin', 'Alan Shepard', 'Neil Armstrong', 'German Titow'] },
  { f: 'Welches Reich errichtete Machu Picchu?', t: 'Geschichte',
    a: ['die Inka', 'die Azteken', 'die Maya', 'die Olmeken'] },
  { f: 'Wer veröffentlichte 1517 die 95 Thesen?', t: 'Geschichte',
    a: ['Martin Luther', 'Johannes Calvin', 'Thomas Müntzer', 'Philipp Melanchthon'] },
  { f: 'Welche Stadt verschüttete der Vesuv im Jahr 79?', t: 'Geschichte',
    a: ['Pompeji', 'Ostia', 'Ravenna', 'Syrakus'] },
  { f: 'Wie hieß der erste künstliche Satellit im Erdorbit?', t: 'Geschichte',
    a: ['Sputnik 1', 'Explorer 1', 'Wostok 1', 'Luna 1'] },
  { f: 'Welcher Vertrag beendete 1919 offiziell den Ersten Weltkrieg?', t: 'Geschichte',
    a: ['Versailler Vertrag', 'Vertrag von Trianon', 'Frieden von Brest-Litowsk', 'Vertrag von Rapallo'] },
  { f: 'Welches Volk erfand das Papier?', t: 'Geschichte',
    a: ['die Chinesen', 'die Ägypter', 'die Römer', 'die Perser'] },
  { f: 'Wer war der erste römische Kaiser?', t: 'Geschichte',
    a: ['Augustus', 'Julius Caesar', 'Nero', 'Tiberius'] },
  { f: 'Welche Königin regierte England von 1558 bis 1603?', t: 'Geschichte',
    a: ['Elisabeth I.', 'Maria I.', 'Victoria', 'Anne'] },
  { f: 'In welchem Jahr wurde die Bundesrepublik Deutschland gegründet?', t: 'Geschichte',
    a: ['1949', '1945', '1948', '1950'] },
  { f: 'Wie hieß die Hauptstadt des Byzantinischen Reichs?', t: 'Geschichte',
    a: ['Konstantinopel', 'Athen', 'Antiochia', 'Thessaloniki'] },
  { f: 'Wessen Expedition umsegelte als erste die Erde?', t: 'Geschichte',
    a: ['Ferdinand Magellan', 'Vasco da Gama', 'Francis Drake', 'James Cook'] },
  { f: 'In welchem Jahr sank die Titanic?', t: 'Geschichte',
    a: ['1912', '1905', '1918', '1923'] },
  { f: 'Welche Dynastie ließ die Verbotene Stadt in Peking bauen?', t: 'Geschichte',
    a: ['Ming', 'Qing', 'Han', 'Tang'] },
  { f: 'Nach wem ist der Staat Bolivien benannt?', t: 'Geschichte',
    a: ['Simón Bolívar', 'José de San Martín', 'Pancho Villa', 'Bernardo O’Higgins'] },
  { f: 'Welcher Krieg dauerte von 1618 bis 1648?', t: 'Geschichte',
    a: ['der Dreißigjährige Krieg', 'der Siebenjährige Krieg', 'der Hundertjährige Krieg', 'der Spanische Erbfolgekrieg'] },
  { f: 'In welchem Jahr landeten die ersten Menschen auf dem Mond?', t: 'Geschichte',
    a: ['1969', '1967', '1971', '1972'] },
  { f: 'Auf welchem Schiff reiste Charles Darwin um die Welt?', t: 'Geschichte',
    a: ['Beagle', 'Endeavour', 'Victoria', 'Discovery'] },
  { f: 'Welche Stadt war bis 1990 Hauptstadt der Bundesrepublik?', t: 'Geschichte',
    a: ['Bonn', 'Frankfurt', 'Köln', 'Stuttgart'] },
  { f: 'Wer war der erste Bundeskanzler der Bundesrepublik?', t: 'Geschichte',
    a: ['Konrad Adenauer', 'Ludwig Erhard', 'Willy Brandt', 'Kurt Georg Kiesinger'] },
  { f: 'Welches Bauwerk wurde 1889 zur Weltausstellung eröffnet?', t: 'Geschichte',
    a: ['Eiffelturm', 'Freiheitsstatue', 'Big Ben', 'Kölner Dom'] },
  { f: 'In welchem Jahrhundert lebte Johann Sebastian Bach?', t: 'Geschichte',
    a: ['im 18.', 'im 16.', 'im 17.', 'im 19.'] },
  { f: 'Welches Land kaufte 1867 Alaska?', t: 'Geschichte',
    a: ['die USA', 'Kanada', 'Großbritannien', 'Dänemark'] },
  { f: 'Über welches Reich herrschte Kleopatra?', t: 'Geschichte',
    a: ['Ägypten', 'Persien', 'Karthago', 'Makedonien'] },
  { f: 'Wann begann der Erste Weltkrieg?', t: 'Geschichte',
    a: ['1914', '1912', '1916', '1918'] },

  /* ── Was lebt ────────────────────────────────────────── */
  { f: 'Wie viele Herzen hat ein Oktopus?', t: 'Natur',
    a: ['drei', 'eins', 'zwei', 'vier'] },
  { f: 'Welches Tier ist das schnellste der Welt?', t: 'Natur',
    a: ['der Wanderfalke', 'der Gepard', 'der Segelfisch', 'die Gabelantilope'] },
  { f: 'Welcher ist der längste Knochen im menschlichen Körper?', t: 'Natur',
    a: ['der Oberschenkelknochen', 'das Schienbein', 'der Oberarmknochen', 'das Wadenbein'] },
  { f: 'Welches Säugetier legt Eier?', t: 'Natur',
    a: ['das Schnabeltier', 'die Fledermaus', 'das Faultier', 'das Gürteltier'] },
  { f: 'Welche Blutgruppe gilt als Universalspender?', t: 'Natur',
    a: ['0 negativ', 'AB positiv', 'A negativ', 'B positiv'] },
  { f: 'Welches Organ produziert Insulin?', t: 'Natur',
    a: ['die Bauchspeicheldrüse', 'die Leber', 'die Niere', 'die Milz'] },
  { f: 'Wie viele Kammern hat das Herz eines Vogels?', t: 'Natur',
    a: ['vier', 'zwei', 'drei', 'fünf'] },
  { f: 'Welches Gas nehmen Pflanzen bei der Fotosynthese auf?', t: 'Natur',
    a: ['Kohlendioxid', 'Sauerstoff', 'Stickstoff', 'Wasserstoff'] },
  { f: 'Welcher Fisch kann sein Geschlecht wechseln?', t: 'Natur',
    a: ['der Clownfisch', 'der Hering', 'der Karpfen', 'der Aal'] },
  { f: 'Welche ist die größte Menschenaffenart?', t: 'Natur',
    a: ['der Gorilla', 'der Orang-Utan', 'der Schimpanse', 'der Bonobo'] },
  { f: 'Welcher Vogel kann rückwärts fliegen?', t: 'Natur',
    a: ['der Kolibri', 'der Specht', 'die Schwalbe', 'der Star'] },
  { f: 'Welche Farbe hat das Blut eines Tintenfischs?', t: 'Natur',
    a: ['blau', 'grün', 'rot', 'gelb'] },
  { f: 'Wie lange ist eine Elefantenkuh trächtig?', t: 'Natur',
    a: ['etwa 22 Monate', 'etwa 12 Monate', 'etwa 16 Monate', 'etwa 30 Monate'] },
  { f: 'Welches Tier hat den höchsten Blutdruck?', t: 'Natur',
    a: ['die Giraffe', 'der Elefant', 'der Blauwal', 'das Nashorn'] },
  { f: 'Wie heißt die Angst vor engen Räumen?', t: 'Natur',
    a: ['Klaustrophobie', 'Agoraphobie', 'Akrophobie', 'Arachnophobie'] },
  { f: 'Wie viele Beine hat ein Insekt?', t: 'Natur',
    a: ['sechs', 'acht', 'vier', 'zehn'] },
  { f: 'Welches Tier schläft immer nur mit einer Gehirnhälfte?', t: 'Natur',
    a: ['der Delfin', 'das Pferd', 'die Giraffe', 'der Otter'] },
  { f: 'Woraus besteht das Skelett eines Hais?', t: 'Natur',
    a: ['aus Knorpel', 'aus Knochen', 'aus Chitin', 'aus Kalk'] },
  { f: 'Welcher Vogel ist der größte der Welt?', t: 'Natur',
    a: ['der Strauß', 'der Kondor', 'der Emu', 'der Albatros'] },
  { f: 'Wie nennt man Tiere, die nur Pflanzen fressen?', t: 'Natur',
    a: ['Herbivoren', 'Karnivoren', 'Omnivoren', 'Detritivoren'] },
  { f: 'Was sammelt eine Biene, um Honig zu machen?', t: 'Natur',
    a: ['Nektar', 'Pollen', 'Harz', 'Tau'] },
  { f: 'Welches Tier hat die längste Lebenserwartung?', t: 'Natur',
    a: ['der Grönlandhai', 'der Elefant', 'der Papagei', 'die Kegelrobbe'] },
  { f: 'Welcher Baum verliert im Herbst seine Nadeln?', t: 'Natur',
    a: ['die Lärche', 'die Fichte', 'die Kiefer', 'die Tanne'] },
  { f: 'Wie viele Augen hat eine Honigbiene?', t: 'Natur',
    a: ['fünf', 'zwei', 'drei', 'acht'] },
  { f: 'Wie heißt es, wenn Wasser unterhalb des Siedepunkts zu Dampf wird?', t: 'Natur',
    a: ['Verdunstung', 'Kondensation', 'Sublimation', 'Resublimation'] },
  { f: 'Welche Pflanze ist fleischfressend?', t: 'Natur',
    a: ['die Venusfliegenfalle', 'der Löwenzahn', 'die Aloe vera', 'der Efeu'] },

  /* ── Wie die Welt funktioniert ───────────────────────── */
  { f: 'Welches Element hat das Symbol „Fe"?', t: 'Wissenschaft',
    a: ['Eisen', 'Blei', 'Fluor', 'Zinn'] },
  { f: 'Wie schnell ist Licht ungefähr?', t: 'Wissenschaft',
    a: ['300 000 km pro Sekunde', '300 000 km pro Stunde', '30 000 km pro Sekunde', '3 Mio. km pro Sekunde'] },
  { f: 'Welches Element ist im Universum am häufigsten?', t: 'Wissenschaft',
    a: ['Wasserstoff', 'Helium', 'Sauerstoff', 'Kohlenstoff'] },
  { f: 'Was misst ein Seismograf?', t: 'Wissenschaft',
    a: ['Erdbeben', 'Luftdruck', 'Windgeschwindigkeit', 'Luftfeuchtigkeit'] },
  { f: 'Welcher Planet ist der heißeste im Sonnensystem?', t: 'Wissenschaft',
    a: ['Venus', 'Merkur', 'Mars', 'Jupiter'] },
  { f: 'Wer entwickelte in Europa den Buchdruck mit beweglichen Lettern?', t: 'Wissenschaft',
    a: ['Johannes Gutenberg', 'William Caxton', 'Aldus Manutius', 'Nikolaus Jenson'] },
  { f: 'Was ist die Einheit der elektrischen Spannung?', t: 'Wissenschaft',
    a: ['Volt', 'Ampere', 'Watt', 'Ohm'] },
  { f: 'Wie viele Bit hat ein Byte?', t: 'Wissenschaft',
    a: ['acht', 'vier', 'sechzehn', 'zehn'] },
  { f: 'Welches Metall ist bei Zimmertemperatur flüssig?', t: 'Wissenschaft',
    a: ['Quecksilber', 'Blei', 'Zinn', 'Zink'] },
  { f: 'Was beschreibt der pH-Wert?', t: 'Wissenschaft',
    a: ['wie sauer oder basisch etwas ist', 'die Temperatur', 'die Dichte', 'die Leitfähigkeit'] },
  { f: 'Welches Teilchen im Atomkern ist elektrisch neutral?', t: 'Wissenschaft',
    a: ['das Neutron', 'das Proton', 'das Elektron', 'das Positron'] },
  { f: 'Welche große Galaxie ist unsere nächste Nachbarin?', t: 'Wissenschaft',
    a: ['Andromeda', 'Dreiecksgalaxie', 'Sombrerogalaxie', 'Whirlpool-Galaxie'] },
  { f: 'Was ist Trockeneis?', t: 'Wissenschaft',
    a: ['gefrorenes Kohlendioxid', 'gefrorener Stickstoff', 'besonders kaltes Wasser', 'gefrorenes Helium'] },
  { f: 'In welcher Einheit misst man Lautstärke?', t: 'Wissenschaft',
    a: ['Dezibel', 'Hertz', 'Watt', 'Lumen'] },
  { f: 'Was ist Graphen?', t: 'Wissenschaft',
    a: ['eine einlagige Schicht aus Kohlenstoff', 'ein Kunststoff', 'ein Edelmetall', 'ein Edelgas'] },
  { f: 'Wofür steht das „L" in LASER?', t: 'Wissenschaft',
    a: ['Light', 'Linear', 'Long', 'Low'] },
  { f: 'Was tut ein Katalysator bei einer Reaktion?', t: 'Wissenschaft',
    a: ['er beschleunigt sie, ohne verbraucht zu werden', 'er verlangsamt sie', 'er wird dabei aufgebraucht', 'er verändert das Ergebnis'] },
  { f: 'Welcher Planet hat die meisten bekannten Monde?', t: 'Wissenschaft',
    a: ['Saturn', 'Jupiter', 'Uranus', 'Neptun'] },
  { f: 'Was misst die Richterskala?', t: 'Wissenschaft',
    a: ['die Stärke von Erdbeben', 'die Windstärke', 'die Höhe von Wellen', 'die Radioaktivität'] },
  { f: 'Welches Gas macht den größten Teil unserer Luft aus?', t: 'Wissenschaft',
    a: ['Stickstoff', 'Sauerstoff', 'Kohlendioxid', 'Argon'] },
  { f: 'Wie heißt der Zustand, in dem ein Stoff vom Festen direkt gasförmig wird?', t: 'Wissenschaft',
    a: ['Sublimation', 'Kondensation', 'Verdampfung', 'Erstarrung'] },
  { f: 'Wie viele Chromosomen hat ein Mensch normalerweise?', t: 'Wissenschaft',
    a: ['46', '23', '48', '44'] },
  { f: 'Was ist ein Lichtjahr?', t: 'Wissenschaft',
    a: ['eine Strecke', 'eine Zeitspanne', 'eine Geschwindigkeit', 'eine Helligkeit'] },
  { f: 'Welches Vitamin bildet der Körper mithilfe von Sonnenlicht?', t: 'Wissenschaft',
    a: ['Vitamin D', 'Vitamin C', 'Vitamin B12', 'Vitamin K'] },
  { f: 'Wie nennt man den Punkt, an dem ein Stoff schmilzt?', t: 'Wissenschaft',
    a: ['Schmelzpunkt', 'Siedepunkt', 'Taupunkt', 'Tripelpunkt'] },
  { f: 'Wer stellte die Gesetze der Planetenbewegung auf?', t: 'Wissenschaft',
    a: ['Johannes Kepler', 'Galileo Galilei', 'Tycho Brahe', 'Nikolaus Kopernikus'] },

  /* ── Gesagt, geschrieben, gespielt ───────────────────── */
  { f: 'Wer schrieb den Roman „Der Prozess"?', t: 'Kultur',
    a: ['Franz Kafka', 'Thomas Mann', 'Hermann Hesse', 'Robert Musil'] },
  { f: 'Welche Sprache hat weltweit die meisten Muttersprachler?', t: 'Kultur',
    a: ['Mandarin', 'Englisch', 'Spanisch', 'Hindi'] },
  { f: 'Wer malte „Sternennacht"?', t: 'Kultur',
    a: ['Vincent van Gogh', 'Claude Monet', 'Paul Cézanne', 'Edvard Munch'] },
  { f: 'Aus welchem Land stammt der Tango?', t: 'Kultur',
    a: ['Argentinien', 'Spanien', 'Brasilien', 'Kuba'] },
  { f: 'Welches Instrument hat 88 Tasten?', t: 'Kultur',
    a: ['das Klavier', 'die Orgel', 'das Akkordeon', 'das Cembalo'] },
  { f: 'Wer komponierte „Die Zauberflöte"?', t: 'Kultur',
    a: ['Mozart', 'Beethoven', 'Haydn', 'Schubert'] },
  { f: 'Wer schrieb „Hundert Jahre Einsamkeit"?', t: 'Kultur',
    a: ['Gabriel García Márquez', 'Mario Vargas Llosa', 'Julio Cortázar', 'Jorge Luis Borges'] },
  { f: 'Welcher Kunstrichtung wird Salvador Dalí zugerechnet?', t: 'Kultur',
    a: ['dem Surrealismus', 'dem Kubismus', 'dem Impressionismus', 'dem Expressionismus'] },
  { f: 'Was ist ein Palindrom?', t: 'Kultur',
    a: ['ein Wort, das vorwärts wie rückwärts gleich ist', 'ein Wort mit doppelter Bedeutung', 'ein erfundenes Wort', 'ein Wort ohne Vokale'] },
  { f: 'Welche dieser Sprachen ist keine romanische?', t: 'Kultur',
    a: ['Griechisch', 'Rumänisch', 'Portugiesisch', 'Katalanisch'] },
  { f: 'Welcher Film gewann 2020 den Oscar als bester Film?', t: 'Kultur',
    a: ['Parasite', '1917', 'Joker', 'Once Upon a Time in Hollywood'] },
  { f: 'Wer schrieb „Der kleine Prinz"?', t: 'Kultur',
    a: ['Antoine de Saint-Exupéry', 'Jules Verne', 'Albert Camus', 'André Gide'] },
  { f: 'Wie viele Zeilen hat ein Sonett?', t: 'Kultur',
    a: ['14', '12', '16', '10'] },
  { f: 'Wer schrieb den Roman „1984"?', t: 'Kultur',
    a: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H. G. Wells'] },
  { f: 'Was bedeutet „carpe diem"?', t: 'Kultur',
    a: ['nutze den Tag', 'der Weg ist das Ziel', 'wer wagt, gewinnt', 'so ist das Leben'] },
  { f: 'Welche Oper stammt von Giuseppe Verdi?', t: 'Kultur',
    a: ['Aida', 'Tosca', 'Carmen', 'Der Freischütz'] },
  { f: 'Aus welcher Sprache kommt das Wort „Keks"?', t: 'Kultur',
    a: ['aus dem Englischen', 'aus dem Französischen', 'aus dem Niederländischen', 'aus dem Türkischen'] },
  { f: 'In welchem Fall steht „dem Mann"?', t: 'Kultur',
    a: ['im Dativ', 'im Genitiv', 'im Akkusativ', 'im Nominativ'] },
  { f: 'Wer schrieb „Die Verwandlung"?', t: 'Kultur',
    a: ['Franz Kafka', 'Stefan Zweig', 'Joseph Roth', 'Alfred Döblin'] },
  { f: 'Welche Band nahm „Dark Side of the Moon" auf?', t: 'Kultur',
    a: ['Pink Floyd', 'Led Zeppelin', 'The Who', 'Deep Purple'] },
  { f: 'Welcher Roman gilt als der längste der Weltliteratur?', t: 'Kultur',
    a: ['Auf der Suche nach der verlorenen Zeit', 'Krieg und Frieden', 'Ulysses', 'Der Zauberberg'] },
  { f: 'Welcher Buchstabe kommt im Deutschen am häufigsten vor?', t: 'Kultur',
    a: ['E', 'N', 'A', 'S'] },
  { f: 'Welche Farbe fehlt im klassischen Regenbogen?', t: 'Kultur',
    a: ['Braun', 'Indigo', 'Violett', 'Orange'] },
  { f: 'Wer schrieb „Die Blechtrommel"?', t: 'Kultur',
    a: ['Günter Grass', 'Heinrich Böll', 'Siegfried Lenz', 'Martin Walser'] },
  { f: 'Welches Museum zeigt „Die Nachtwache" von Rembrandt?', t: 'Kultur',
    a: ['das Rijksmuseum', 'der Louvre', 'die Uffizien', 'der Prado'] },

  /* ── Spiel und Sport ─────────────────────────────────── */
  { f: 'Wie viele Spieler stehen beim Volleyball je Team auf dem Feld?', t: 'Sport',
    a: ['sechs', 'fünf', 'sieben', 'vier'] },
  { f: 'Wie lang ist ein Marathon?', t: 'Sport',
    a: ['42,195 km', '40 km', '45 km', '38,6 km'] },
  { f: 'Aus welcher Sportart stammt der Begriff „Hattrick" ursprünglich?', t: 'Sport',
    a: ['Cricket', 'Fußball', 'Eishockey', 'Handball'] },
  { f: 'Welche Stadt richtete 1972 die Olympischen Sommerspiele aus?', t: 'Sport',
    a: ['München', 'Montreal', 'Moskau', 'Mexiko-Stadt'] },
  { f: 'Wie hoch hängt ein Basketballkorb?', t: 'Sport',
    a: ['3,05 m', '2,80 m', '3,50 m', '2,50 m'] },
  { f: 'Welcher Fußballer wird „der Kaiser" genannt?', t: 'Sport',
    a: ['Franz Beckenbauer', 'Gerd Müller', 'Uwe Seeler', 'Lothar Matthäus'] },
  { f: 'Wie viele Punkte bringt ein Touchdown im American Football?', t: 'Sport',
    a: ['sechs', 'sieben', 'drei', 'vier'] },
  { f: 'Welches Grand-Slam-Turnier wird auf Rasen gespielt?', t: 'Sport',
    a: ['Wimbledon', 'die French Open', 'die US Open', 'die Australian Open'] },
  { f: 'Wie viele Spieler stehen beim Handball je Team auf dem Feld?', t: 'Sport',
    a: ['sieben', 'sechs', 'fünf', 'acht'] },
  { f: 'Wie lange dauert ein Drittel beim Eishockey?', t: 'Sport',
    a: ['20 Minuten', '15 Minuten', '25 Minuten', '30 Minuten'] },
  { f: 'Wie viele Löcher hat ein normaler Golfplatz?', t: 'Sport',
    a: ['18', '9', '12', '24'] },
  { f: 'In welchem Land wurde Judo entwickelt?', t: 'Sport',
    a: ['Japan', 'China', 'Korea', 'Thailand'] },
  { f: 'Wie viele Figuren hat ein Spieler beim Schach zu Beginn?', t: 'Sport',
    a: ['16', '12', '18', '20'] },
  { f: 'Welche Farbe hat der Ball beim Snooker mit dem höchsten Wert?', t: 'Sport',
    a: ['Schwarz', 'Pink', 'Blau', 'Braun'] },
  { f: 'Alle wie viele Jahre finden die Olympischen Winterspiele statt?', t: 'Sport',
    a: ['alle vier Jahre', 'alle zwei Jahre', 'alle drei Jahre', 'alle fünf Jahre'] },

  /* ── Was auf den Tisch kommt ─────────────────────────── */
  { f: 'Woraus besteht Marzipan hauptsächlich?', t: 'Essen',
    a: ['aus Mandeln', 'aus Haselnüssen', 'aus Kokos', 'aus Cashews'] },
  { f: 'Welche Nudelsorte ist röhrenförmig?', t: 'Essen',
    a: ['Penne', 'Farfalle', 'Fusilli', 'Orecchiette'] },
  { f: 'Woraus wird Tofu gemacht?', t: 'Essen',
    a: ['aus Sojabohnen', 'aus Kichererbsen', 'aus Reis', 'aus Weizen'] },
  { f: 'Welches Gewürz ist das teuerste der Welt?', t: 'Essen',
    a: ['Safran', 'Vanille', 'Kardamom', 'Zimt'] },
  { f: 'Was ist Rooibos?', t: 'Essen',
    a: ['ein Tee aus Südafrika', 'eine Kaffeesorte', 'ein Gewürz', 'eine Zitrusfrucht'] },
  { f: 'Welche dieser Früchte ist botanisch eine Beere?', t: 'Essen',
    a: ['die Banane', 'die Erdbeere', 'die Himbeere', 'die Brombeere'] },
  { f: 'Aus welchem Getreide wird klassisches Bier gebraut?', t: 'Essen',
    a: ['aus Gerste', 'aus Weizen', 'aus Roggen', 'aus Hafer'] },
  { f: 'Was bezeichnet „Umami"?', t: 'Essen',
    a: ['eine Geschmacksrichtung', 'eine Nudelsorte', 'eine Sushi-Art', 'ein Küchenmesser'] },
  { f: 'Aus welchem Land stammt Feta ursprünglich?', t: 'Essen',
    a: ['aus Griechenland', 'aus der Türkei', 'aus Bulgarien', 'aus Italien'] },
  { f: 'Welche Zutat gehört nicht in eine klassische Carbonara?', t: 'Essen',
    a: ['Sahne', 'Ei', 'Pecorino', 'Guanciale'] },
  { f: 'Was ist Wasabi botanisch?', t: 'Essen',
    a: ['ein Kreuzblütler', 'eine Alge', 'ein Pilz', 'eine Chilisorte'] },
  { f: 'Welcher Käse hat traditionell Löcher?', t: 'Essen',
    a: ['Emmentaler', 'Gouda', 'Camembert', 'Cheddar'] },
  { f: 'Aus welchem Land kommt Paella?', t: 'Essen',
    a: ['aus Spanien', 'aus Portugal', 'aus Mexiko', 'aus Italien'] },
  { f: 'Welches Teil der Muskatnuss ist Macis?', t: 'Essen',
    a: ['der Samenmantel', 'die Schale', 'die Wurzel', 'das Blatt'] },
  { f: 'Was passiert beim Fermentieren?', t: 'Essen',
    a: ['Mikroorganismen bauen Zucker um', 'Wasser wird entzogen', 'Eiweiß gerinnt', 'Fett wird abgespalten'] },

  /* ── Der ganz normale Kram ───────────────────────────── */
  { f: 'Welche Farbe ergibt sich aus Rot und Blau?', t: 'Alltag',
    a: ['Violett', 'Braun', 'Grün', 'Orange'] },
  { f: 'Wie viele Minuten hat ein Fußballspiel ohne Nachspielzeit?', t: 'Alltag',
    a: ['90', '80', '100', '120'] },
  { f: 'Welche Blutgruppe ist in Deutschland am häufigsten?', t: 'Alltag',
    a: ['A positiv', '0 positiv', 'B positiv', 'AB negativ'] },
  { f: 'Was bedeutet die Abkürzung „PDF"?', t: 'Alltag',
    a: ['Portable Document Format', 'Print Document File', 'Public Data Format', 'Personal Digital File'] },
  { f: 'Welche Himmelsrichtung zeigt die Kompassnadel an?', t: 'Alltag',
    a: ['Norden', 'Süden', 'Osten', 'Westen'] },
  { f: 'Was misst ein Barometer?', t: 'Alltag',
    a: ['den Luftdruck', 'die Temperatur', 'die Luftfeuchtigkeit', 'die Windrichtung'] },
  { f: 'Wie viele Tasten hat ein Standard-Zehnerblock?', t: 'Alltag',
    a: ['17', '12', '15', '20'] },
  { f: 'Welche Blutgefäße sind am dünnsten?', t: 'Alltag',
    a: ['die Kapillaren', 'die Venen', 'die Arterien', 'die Aorta'] },
  { f: 'Was bedeutet „WLAN" ausgeschrieben auf Deutsch?', t: 'Alltag',
    a: ['drahtloses lokales Netzwerk', 'weltweites Netzwerk', 'schnelles Heimnetz', 'kabelloses Telefonnetz'] },
  { f: 'Welches Verkehrsschild ist dreieckig mit rotem Rand?', t: 'Alltag',
    a: ['ein Gefahrenzeichen', 'ein Verbotszeichen', 'ein Gebotszeichen', 'ein Hinweiszeichen'] },
  { f: 'Wie viele Nullen hat eine Milliarde?', t: 'Alltag',
    a: ['neun', 'sechs', 'zwölf', 'acht'] },
  { f: 'Welche Währung gilt in Schweden?', t: 'Alltag',
    a: ['Krone', 'Euro', 'Mark', 'Gulden'] },
  { f: 'Was steht im Bruch oben?', t: 'Alltag',
    a: ['der Zähler', 'der Nenner', 'der Divisor', 'der Rest'] },
  { f: 'Wie viele Grad hat die Winkelsumme im Dreieck?', t: 'Alltag',
    a: ['180', '90', '270', '360'] },
  { f: 'Welche Blutgefäße führen Blut zum Herzen hin?', t: 'Alltag',
    a: ['die Venen', 'die Arterien', 'die Kapillaren', 'die Lymphgefäße'] }
];

/**
 * Schätzfragen. `w` ist der wahre Wert, `e` die Einheit — die steht neben
 * dem Eingabefeld, damit niemand rät, ob Meter oder Kilometer gemeint sind.
 * `z` erscheint erst nach der Antwort und ist das kleine Detail, das man
 * hinterher weitererzählt.
 */
export const SCHAETZEN = [
  { f: 'Wie hoch ist der Eiffelturm?', w: 330, e: 'm', t: 'Bauwerke',
    z: 'Ohne Antenne sind es 300 Meter — die Spitze wächst mit der Technik.' },
  { f: 'Wie tief ist die tiefste Stelle des Marianengrabens?', w: 10994, e: 'm', t: 'Erde',
    z: 'Der Mount Everest hätte darin noch über zwei Kilometer Luft nach oben.' },
  { f: 'Wie viele Menschen leben in Deutschland?', w: 83500000, e: 'Menschen', t: 'Länder',
    z: 'Etwa jede fünfzehnte Person in der EU.' },
  { f: 'Wie lang ist die Chinesische Mauer inklusive aller Abzweige?', w: 21196, e: 'km', t: 'Bauwerke',
    z: 'Gut die halbe Strecke einmal um die Erde.' },
  { f: 'Wie weit ist der Mond im Mittel von der Erde entfernt?', w: 384400, e: 'km', t: 'Weltall',
    z: 'Alle acht Planeten des Sonnensystems passen nebeneinander dazwischen.' },
  { f: 'Wie schnell fliegt ein Passagierflugzeug auf Reiseflughöhe?', w: 900, e: 'km/h', t: 'Technik',
    z: 'Knapp unter der Schallgeschwindigkeit in dieser Höhe.' },
  { f: 'Wie viele Mitgliedsstaaten hat die UNO?', w: 193, e: 'Staaten', t: 'Länder',
    z: 'Der Vatikan und Palästina sind Beobachter, keine Mitglieder.' },
  { f: 'Wie alt wurde der älteste sicher belegte Mensch?', w: 122, e: 'Jahre', t: 'Menschen',
    z: 'Jeanne Calment aus Arles, gestorben 1997.' },
  { f: 'Wie viel Blut hat ein erwachsener Mensch?', w: 5.5, e: 'Liter', t: 'Menschen',
    z: 'Etwa acht Prozent des Körpergewichts.' },
  { f: 'Wie hoch ist der Mount Everest?', w: 8849, e: 'm', t: 'Erde',
    z: 'Seit der Neuvermessung 2020 gilt diese Zahl — vorher 8848.' },
  { f: 'Wie viele Sprachen werden weltweit gesprochen?', w: 7000, e: 'Sprachen', t: 'Kultur',
    z: 'Etwa die Hälfte davon hat weniger als tausend Sprecher.' },
  { f: 'Wie lang ist der Nil?', w: 6650, e: 'km', t: 'Erde',
    z: 'Ob er oder der Amazonas länger ist, streiten Fachleute bis heute.' },
  { f: 'Wie schwer ist ein ausgewachsener Blauwal?', w: 150000, e: 'kg', t: 'Tiere',
    z: 'Allein die Zunge wiegt so viel wie ein Elefant.' },
  { f: 'Wie viele Menschen leben in der Metropolregion Tokio?', w: 37000000, e: 'Menschen', t: 'Länder',
    z: 'Mehr als in ganz Kanada.' },
  { f: 'Wie viele Muskeln hat der menschliche Körper ungefähr?', w: 650, e: 'Muskeln', t: 'Menschen',
    z: 'Der kleinste sitzt im Ohr und ist gut einen Millimeter lang.' },
  { f: 'Wie viele Sekunden hat ein Tag?', w: 86400, e: 'Sekunden', t: 'Zahlen',
    z: '60 mal 60 mal 24 — und alle paar Jahre eine Schaltsekunde mehr.' },
  { f: 'Wie groß ist der Erdumfang am Äquator?', w: 40075, e: 'km', t: 'Erde',
    z: 'Der Meter wurde ursprünglich so definiert, dass es rund 40 000 werden.' },
  { f: 'Wie heiß ist die Oberfläche der Sonne?', w: 5500, e: '°C', t: 'Weltall',
    z: 'Im Kern sind es 15 Millionen Grad.' },
  { f: 'Wie viele Eier legt eine Legehenne im Jahr?', w: 300, e: 'Eier', t: 'Tiere',
    z: 'Wildhühner kommen auf etwa zwanzig.' },
  { f: 'Wie viel Prozent der Erdoberfläche sind von Wasser bedeckt?', w: 71, e: '%', t: 'Erde',
    z: 'Davon sind 97 Prozent Salzwasser.' },
  { f: 'Wie schnell rennt ein Gepard im Sprint?', w: 110, e: 'km/h', t: 'Tiere',
    z: 'Aber nur für etwa 30 Sekunden, dann überhitzt er.' },
  { f: 'Wie alt ist die Erde?', w: 4540, e: 'Mio. Jahre', t: 'Erde',
    z: 'Gemessen an den ältesten Meteoriten aus derselben Staubwolke.' },
  { f: 'Wie viele Halswirbel hat eine Giraffe?', w: 7, e: 'Wirbel', t: 'Tiere',
    z: 'Genauso viele wie ein Mensch — nur jeder einzelne bis zu 25 cm lang.' },
  { f: 'Wie lange braucht Merkur einmal um die Sonne?', w: 88, e: 'Tage', t: 'Weltall',
    z: 'Ein Merkurtag dauert dagegen 176 Erdtage.' },
  { f: 'Wie viel Wasser steckt in einem Kilo Rindfleisch?', w: 15000, e: 'Liter', t: 'Umwelt',
    z: 'Das meiste davon geht ins Futter, nicht in den Trog.' },
  { f: 'Wie viele Stufen führen im Eiffelturm bis zur zweiten Etage?', w: 674, e: 'Stufen', t: 'Bauwerke',
    z: 'Bis ganz oben geht nur der Aufzug.' },
  { f: 'Wie viel wiegt ein Fußball nach Regelwerk?', w: 430, e: 'g', t: 'Sport',
    z: 'Erlaubt sind 410 bis 450 Gramm.' },
  { f: 'Wie viele Kilokalorien hat eine Banane pro 100 g?', w: 89, e: 'kcal', t: 'Essen',
    z: 'Eine mittlere Banane wiegt geschält etwa 120 Gramm.' },
  { f: 'Wie viele Zuschauer fasst das Wembley-Stadion?', w: 90000, e: 'Plätze', t: 'Sport',
    z: 'Das größte Stadion Europas nach dem Camp Nou.' },
  { f: 'Wie viele Zeichen darf ein Beitrag auf X standardmäßig haben?', w: 280, e: 'Zeichen', t: 'Technik',
    z: 'Bis 2017 waren es nur 140.' },
  { f: 'Wie lang ist ein Fußballfeld typischerweise?', w: 105, e: 'm', t: 'Sport',
    z: 'Bei internationalen Spielen sind 105 mal 68 Meter vorgeschrieben.' },
  { f: 'Wie hoch fliegt ein Passagierflugzeug auf Reiseflughöhe?', w: 11000, e: 'm', t: 'Technik',
    z: 'Da oben ist es etwa minus 55 Grad kalt.' },
  { f: 'Wie viel Wasser fasst eine normale Badewanne?', w: 150, e: 'Liter', t: 'Alltag',
    z: 'Ein Duschbad kommt mit rund 50 Litern aus.' },
  { f: 'Wie viele Haare hat ein Mensch auf dem Kopf?', w: 100000, e: 'Haare', t: 'Menschen',
    z: 'Blonde haben mehr, rote deutlich weniger.' },
  { f: 'Wie weit ist die Sonne von der Erde entfernt?', w: 150, e: 'Mio. km', t: 'Weltall',
    z: 'Genau diese Strecke heißt „eine Astronomische Einheit".' },
  { f: 'Wie lange braucht Licht von Proxima Centauri zu uns?', w: 4.2, e: 'Jahre', t: 'Weltall',
    z: 'Der nächste Stern nach der Sonne — und trotzdem unerreichbar weit.' },
  { f: 'Wie viel Alkohol hat ein klassisches Pils?', w: 4.8, e: '%', t: 'Essen',
    z: 'Ein Weizen liegt meist etwas darüber.' },
  { f: 'Wie viele Kilometer läuft ein Fußballprofi pro Spiel?', w: 11, e: 'km', t: 'Sport',
    z: 'Mittelfeldspieler kommen auf mehr als Innenverteidiger.' },
  { f: 'Wie alt kann eine Riesenschildkröte werden?', w: 150, e: 'Jahre', t: 'Tiere',
    z: 'Jonathan auf St. Helena ist seit 1832 dabei.' },
  { f: 'Wie viele Menschen leben auf der Erde?', w: 8200000000, e: 'Menschen', t: 'Länder',
    z: 'Die achte Milliarde wurde im November 2022 voll.' },
  { f: 'Wie lang ist der Eurotunnel unter dem Ärmelkanal?', w: 50, e: 'km', t: 'Bauwerke',
    z: '38 davon liegen unter dem Meer.' },
  { f: 'Wie viele Stufen führen in der Freiheitsstatue bis zur Krone?', w: 354, e: 'Stufen', t: 'Bauwerke',
    z: 'Vom Sockel aus gezählt — der Aufzug endet weiter unten.' },
  { f: 'Wie schwer ist ein ausgewachsener afrikanischer Elefantenbulle?', w: 6000, e: 'kg', t: 'Tiere',
    z: 'Er frisst dafür bis zu 300 Kilo Pflanzen am Tag.' },
  { f: 'Wie stark ist die Erdachse geneigt?', w: 23.4, e: 'Grad', t: 'Erde',
    z: 'Genau daher kommen die Jahreszeiten.' },
  { f: 'Wie viel Luft atmet ein Mensch am Tag?', w: 12000, e: 'Liter', t: 'Menschen',
    z: 'Etwa 20 000 Atemzüge.' },
  { f: 'Wie schwer ist ein menschliches Gehirn?', w: 1400, e: 'g', t: 'Menschen',
    z: 'Es verbraucht ein Fünftel der gesamten Energie des Körpers.' },
  { f: 'Wie viele Spiele hat ein Bundesliga-Team pro Saison?', w: 34, e: 'Spiele', t: 'Sport',
    z: '18 Vereine, jeder zweimal gegen jeden.' },
  { f: 'Wie lange dauert ein Marsjahr in Erdtagen?', w: 687, e: 'Tage', t: 'Weltall',
    z: 'Ein Marstag ist dagegen fast so lang wie unserer.' },
  { f: 'Wie hoch ist der Salto Ángel, der höchste Wasserfall der Erde?', w: 979, e: 'm', t: 'Erde',
    z: 'Das Wasser zerstäubt auf dem Weg nach unten fast vollständig.' },
  { f: 'Wie viel Kaffee trinkt ein Mensch in Deutschland pro Jahr?', w: 168, e: 'Liter', t: 'Essen',
    z: 'Mehr als Bier und Mineralwasser.' },
  { f: 'Wie viele Zuschauer fasst der Signal-Iduna-Park in Dortmund?', w: 81365, e: 'Plätze', t: 'Sport',
    z: 'Die Südtribüne allein nimmt fast 25 000 Stehplätze auf.' },
  { f: 'Wie hoch ist der Kölner Dom?', w: 157, e: 'm', t: 'Bauwerke',
    z: 'Von 1880 bis 1884 war er das höchste Gebäude der Welt.' },
  { f: 'Wie lang ist der Rhein?', w: 1233, e: 'km', t: 'Erde',
    z: 'Seit einer Korrektur 2010 gilt diese Zahl, vorher hieß es 1320.' },
  { f: 'Wie tief ist der Bodensee an der tiefsten Stelle?', w: 251, e: 'm', t: 'Erde',
    z: 'Er fasst mehr Süßwasser als jeder andere See Mitteleuropas.' },
  { f: 'Wie schnell fährt ein ICE 3 im Regelbetrieb maximal?', w: 300, e: 'km/h', t: 'Technik',
    z: 'Auf der Strecke Köln–Frankfurt wird das tatsächlich ausgefahren.' },
  { f: 'Wie lange dauerte der Bau des Kölner Doms insgesamt?', w: 632, e: 'Jahre', t: 'Bauwerke',
    z: 'Von 1248 bis 1880, mit 300 Jahren Baustopp dazwischen.' },
  { f: 'Wie groß ist der Durchmesser der Erde am Äquator?', w: 12742, e: 'km', t: 'Erde',
    z: 'Von Pol zu Pol sind es 43 Kilometer weniger.' },
  { f: 'Wie viele Kilokalorien hat eine Tafel Vollmilchschokolade?', w: 540, e: 'kcal', t: 'Essen',
    z: 'Pro 100 Gramm — also pro ganzer Tafel.' },
  { f: 'Wie lange braucht Licht von der Sonne bis zur Erde?', w: 500, e: 'Sekunden', t: 'Weltall',
    z: 'Gut acht Minuten. Man sieht die Sonne immer, wie sie eben war.' },
  { f: 'Wie viele Menschen leben in Österreich?', w: 9200000, e: 'Menschen', t: 'Länder',
    z: 'Etwa jeder Fünfte davon in Wien.' },
  { f: 'Wie hoch ist der Burj Khalifa in Dubai?', w: 828, e: 'm', t: 'Bauwerke',
    z: 'Wer unten steht und oben ist, sieht den Sonnenuntergang zweimal.' },
  { f: 'Wie viele Passagiere fasst ein Airbus A380 maximal?', w: 853, e: 'Passagiere', t: 'Technik',
    z: 'In der üblichen Bestuhlung sind es eher 500.' },
  { f: 'Wie weit fliegt eine Küstenseeschwalbe pro Jahr?', w: 70000, e: 'km', t: 'Tiere',
    z: 'Sie zieht von der Arktis in die Antarktis und zurück.' },
  { f: 'Wie viel Trinkwasser verbraucht ein Haushalt pro Person und Tag?', w: 125, e: 'Liter', t: 'Umwelt',
    z: 'Nur etwa vier Liter davon landen wirklich im Glas.' },
  { f: 'Wie breit ist ein Fußballtor?', w: 732, e: 'cm', t: 'Sport',
    z: 'Acht Yards — die Maße stammen noch aus England.' },
  { f: 'Wie viele Amtssprachen hat Indien auf Bundesebene anerkannt?', w: 22, e: 'Sprachen', t: 'Kultur',
    z: 'Dazu kommen hunderte, die keinen offiziellen Status haben.' },
  { f: 'Wie tief kann ein Pottwal tauchen?', w: 2000, e: 'm', t: 'Tiere',
    z: 'Und dabei über eine Stunde die Luft anhalten.' },
  { f: 'Wie viele Inseln gehören zu Griechenland?', w: 6000, e: 'Inseln', t: 'Länder',
    z: 'Bewohnt sind davon nur etwa 230.' },
  { f: 'Wie viele Knochen hat ein Neugeborenes?', w: 305, e: 'Knochen', t: 'Menschen',
    z: 'Bis zum Erwachsenenalter wachsen viele davon zusammen.' },
  { f: 'Wie oft schlägt ein Kolibriherz pro Minute im Flug?', w: 1200, e: 'Schläge', t: 'Tiere',
    z: 'Nachts fällt der Puls auf ein Zehntel davon.' },
  { f: 'Wie viele Wörter stehen ungefähr im Duden?', w: 148000, e: 'Wörter', t: 'Kultur',
    z: 'Der gesamte deutsche Wortschatz wird auf ein Vielfaches geschätzt.' },
  { f: 'Wie viele Zähne hat ein Weißer Hai gleichzeitig im Maul?', w: 300, e: 'Zähne', t: 'Tiere',
    z: 'In Reihen hintereinander — nachrücken inklusive.' },
  { f: 'Wie kalt ist der absolute Nullpunkt in Celsius?', w: -273, e: '°C', t: 'Wissenschaft',
    z: 'Genau minus 273,15 — kälter geht physikalisch nicht.' },
  { f: 'Wie viele Kilometer fährt ein Auto in Deutschland im Jahr?', w: 13000, e: 'km', t: 'Alltag',
    z: 'Diesel deutlich mehr, Benziner weniger.' },
  { f: 'Wie viele Kalorien verbrennt eine Stunde lockeres Joggen?', w: 600, e: 'kcal', t: 'Sport',
    z: 'Hängt stark am Gewicht — schwerer heißt mehr.' },
  { f: 'Wie viele Stufen hat der Kölner Dom bis zur Turmspitze?', w: 533, e: 'Stufen', t: 'Bauwerke',
    z: 'Wendeltreppe, ohne Aufzug, mit Gegenverkehr.' },
  { f: 'Wie viele Sterne sind insgesamt mit bloßem Auge sichtbar?', w: 9000, e: 'Sterne', t: 'Weltall',
    z: 'Von einem Ort aus sieht man höchstens die Hälfte davon — der Rest steht unter dem Horizont.' },
  { f: 'Wie hoch ist der Wasseranteil im menschlichen Körper?', w: 60, e: '%', t: 'Menschen',
    z: 'Bei Neugeborenen sind es fast drei Viertel.' },
  { f: 'Wie viele Zutaten hat ein Bier nach dem Reinheitsgebot?', w: 4, e: 'Zutaten', t: 'Essen',
    z: 'Wasser, Malz, Hopfen — und die Hefe, die man damals nicht kannte.' },
  { f: 'Wie lange dauert ein Umlauf der Sonne um das Zentrum der Milchstraße?', w: 225, e: 'Mio. Jahre', t: 'Weltall',
    z: 'Beim letzten Mal liefen hier Dinosaurier herum.' },
  { f: 'Wie viele Bahnhöfe hat die Berliner U-Bahn?', w: 175, e: 'Bahnhöfe', t: 'Alltag',
    z: 'Auf neun Linien und gut 155 Kilometern.' },
  { f: 'Wie viel Prozent der Weltbevölkerung leben in Städten?', w: 57, e: '%', t: 'Länder',
    z: '1950 war es noch etwa ein Drittel.' },
  { f: 'Wie viele Tasten hat eine deutsche Standardtastatur?', w: 105, e: 'Tasten', t: 'Technik',
    z: 'Die amerikanische kommt mit 104 aus.' },
  { f: 'Wie lange lebt eine Arbeitsbiene im Sommer?', w: 40, e: 'Tage', t: 'Tiere',
    z: 'Winterbienen dagegen mehrere Monate.' },
  { f: 'Wie viele Liter Wasser stecken in einer Tasse Kaffee samt Anbau?', w: 130, e: 'Liter', t: 'Umwelt',
    z: 'Fast alles davon fällt auf der Plantage an.' },
  { f: 'Wie viel wiegt ein Kubikmeter Luft auf Meereshöhe?', w: 1.2, e: 'kg', t: 'Alltag',
    z: 'Das Zimmer über dir wiegt damit gut fünfzig Kilo.' },
  { f: 'Wie viele Sprachen spricht die Europäische Union offiziell?', w: 24, e: 'Sprachen', t: 'Kultur',
    z: 'Jedes Dokument muss in alle übersetzt werden.' },
  { f: 'Wie viele Kilometer Fahrradwege hat die Stadt Kopenhagen?', w: 390, e: 'km', t: 'Alltag',
    z: 'Mehr Fahrräder als Autos, seit über zehn Jahren.' },
  { f: 'Wie viel Grad Celsius sind 100 Grad Fahrenheit?', w: 38, e: '°C', t: 'Wissenschaft',
    z: 'Fahrenheit legte 100 ungefähr auf die Körpertemperatur.' },
  { f: 'Wie viel wiegt ein Liter Honig?', w: 1.4, e: 'kg', t: 'Essen',
    z: 'Deutlich schwerer als Wasser — deshalb steht auf Gläsern Gewicht, nicht Volumen.' },
  { f: 'Wie viele Satelliten umkreisen aktiv die Erde?', w: 11000, e: 'Satelliten', t: 'Technik',
    z: 'Dazu kommen zehntausende Trümmerteile, die niemand mehr steuert.' },
  { f: 'Wie viele Schafe leben in Neuseeland?', w: 24000000, e: 'Schafe', t: 'Länder',
    z: 'Rund fünf pro Einwohner — in den 1980ern waren es zwanzig.' },
  { f: 'Wie viele Wörter hat der durchschnittliche aktive Wortschatz im Deutschen?', w: 12000, e: 'Wörter', t: 'Kultur',
    z: 'Passiv versteht man ein Vielfaches davon.' },
  { f: 'Wie hoch war die höchste je von einer Boje gemessene Welle?', w: 19, e: 'm', t: 'Erde',
    z: 'Gemessen 2013 im Nordatlantik zwischen Island und Großbritannien.' },
  { f: 'Wie viele Liter Wasser fließen pro Sekunde über die Niagarafälle?', w: 2400000, e: 'Liter', t: 'Erde',
    z: 'Nachts wird ein Teil für Kraftwerke abgezweigt.' },
  { f: 'Wie lange dauert es, bis eine Plastikflasche zerfallen ist?', w: 450, e: 'Jahre', t: 'Umwelt',
    z: 'Und selbst dann bleibt sie als Mikroplastik erhalten.' },
  { f: 'Wie viele Bienen braucht es für ein Glas Honig?', w: 10000, e: 'Bienen', t: 'Tiere',
    z: 'Eine einzelne Biene schafft in ihrem Leben etwa einen Teelöffel.' },
  { f: 'Wie viele Kilometer ist die Grenze zwischen Deutschland und Österreich lang?', w: 815, e: 'km', t: 'Länder',
    z: 'Die längste Außengrenze Deutschlands.' }
];

/** Ein Punktedeckel je Frage — beide Sorten zählen gleich viel. */
export const MAX_PRO_FRAGE = 150;
export const FRAGEN_PRO_RUNDE = 3;
export const ZEIT_WISSEN = 15;      // Sekunden
export const ZEIT_SCHAETZEN = 25;

/**
 * Punkte für eine Wissensfrage: Richtig zählt, schnell zählt etwas dazu.
 * Zwei Drittel für die Antwort, ein Drittel für das Tempo — sonst gewinnt,
 * wer hektisch tippt, statt zu wissen.
 */
export function punkteWissen(richtig, restSekunden) {
  if (!richtig) return 0;
  const rest = Math.max(0, Math.min(ZEIT_WISSEN, restSekunden));
  return Math.round(100 + 50 * (rest / ZEIT_WISSEN));
}

/**
 * Punkte für eine Schätzfrage.
 *
 * Gemessen wird der relative Abstand, nicht der absolute: Bei „wie hoch ist
 * der Everest" sind 200 Meter daneben eine gute Schätzung, bei „wie viel
 * wiegt ein Fußball" sind 200 Gramm daneben eine Katastrophe. Wer bis auf
 * drei Prozent herankommt, bekommt alles; ab achtzig Prozent Abweichung
 * gibt es nichts mehr.
 */
export function punkteSchaetzen(tipp, wahr) {
  if (!Number.isFinite(tipp)) return 0;
  const spanne = Math.max(Math.abs(wahr), 1);
  const ab = Math.abs(tipp - wahr) / spanne;
  if (ab <= 0.03) return MAX_PRO_FRAGE;
  return Math.round(MAX_PRO_FRAGE * Math.max(0, 1 - ab / 0.8));
}

/** „12 % daneben" — die Zeile, die nach jeder Schätzung erscheint. */
export function abweichung(tipp, wahr) {
  const spanne = Math.max(Math.abs(wahr), 1);
  return Math.round((Math.abs(tipp - wahr) / spanne) * 100);
}
